"""empty message

Revision ID: 499666dc4c98
Revises: 00e0986b1b6b
Create Date: 2024-03-21 18:41:12.079777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499666dc4c98'
down_revision = '00e0986b1b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('climate', sa.String(length=120), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('climate')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planets')
    # ### end Alembic commands ###
